project:
  type: book

book:
  title: "Portfolio Computationele Biologie"
  author: "Jouw naam"
  date: "September 2027 - Februari 2028"
  chapters:
    - index.qmd
    - Port2_Theory.qmd
    - Port_logpH_Theory.qmd
    - Differentiaalvergelijkingen_theorie.qmd
    - references.qmd
  appendices:
    - Port2_Pract.qmd
    - Port_logpH_Pract.qmd
    - bradford_statistiek.qmd
    - Sepia_Mantel.qmd  

    
format:
  live-html:
    css: styles.css

engine: knitr

bibliography: references.bib
link-citations: true


editor: visual

language: 
  ui: 
    chapter_name: "" 
    
# resources:
#   - evo-devo/
  
filters:
  - webr

