project:
  type: book

book:
  title: "Portfolio Computationele Biologie"
  author: "Jouw naam"
  date: "September 2027 - Februari 2028"
  chapters:
    - index.qmd
    - Port2_Theory.qmd
<<<<<<< HEAD
    - Port_logpH_Theory.qmd
=======
    - log_pH.qmd
>>>>>>> 4e16669bde8243fd54892dc977db95f4313c7d67
    - Differentiaalvergelijkingen_theorie.qmd
    - references.qmd
  appendices:
    - Port2_Pract.qmd
<<<<<<< HEAD
    - Port_logpH_Pract.qmd
=======
    - bradford_statistiek.qmd
>>>>>>> 4e16669bde8243fd54892dc977db95f4313c7d67
    - Sepia_Mantel.qmd  

    
format:
  live-html:
    css: styles.css

engine: knitr

bibliography: references.bib


editor: visual

language: 
  ui: 
    chapter_name: "" 
    
resources:
  - evo-devo/
  
filters:
  - webr

