project:
  type: book
  
format:
  html:
    css: styles.css


book:
  title: "Portfolio Computationele Biologie"
  author: "Jouw naam"
  date: today
  description: "September 2026 – Februari 2027"
  chapters:
    - index.qmd
    - Port2_Theory.qmd
    - Port_logpH_Theory.qmd
    - Regressie_theorie.qmd
    - Differentiaalvergelijkingen_theorie.qmd
    - sepia_standaardfout_theorie.qmd
    - genetic_drift.qmd
    - references.qmd
  appendices:
    - Port2_Pract.qmd
    - Port_logpH_Pract.qmd
    - Bradford_statistiek.qmd
    - Sepia_Mantel.qmd  

  
engine: knitr

bibliography: references.bib
link-citations: true

number-sections: true

crossref:
  chapters: true
  exr-prefix: "Vraag"
  eq-prefix: "Vergelijking"
  fig-prefix: "Figuur"
  sec-prefix: "Hoofdstuk"

editor: visual
language:
  ui:
    chapter_name: ""
  crossref-exr-title: "Vraag"
  crossref-ch-title: "Hoofdstuk"
  crossref-sec-prefix: "Hoofdstuk"
  crossref-sec-title: "Hoofdstuk"

filters:
  - webr
